### ISSUE TITLE
db:create always returns with exit code 1

### ISSUE THREAD

**Issue by pc-jedi** [db-migrate/node-db-migrate#550]
## I'm submitting a...

 - [x] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior
`db-migrate db:create asdf` return with exit code 1

## Expected behavior
`db-migrate db:create asdf` return with exit code 0

## What is the motivation / use case for changing the behavior?
Exit code else then 0 stands for an error. Therefore some tools fail if the called command exits with error (return code not 0).

## Environment

<pre><code>
db-migrate version: 0.10.5

Additional information:
- Node version: v9.7.1
- Platform: Linux
</code></pre>

**Comment by ollyjshaw** [comment]
👍 I'm looking at using db-migrate in a build pipeline.

**Comment by oroce** [comment]
I'm having the same issue, it seems the exit code 1 is hardcoded: https://github.com/db-migrate/node-db-migrate/blob/master/lib/commands/db.js#L35

**Comment by wzrdtales** [comment]
Thanks for reporting, yes this is an unwanted bug.

**Comment by northern** [comment]
I experience this same behaviour when I run db-migrate with a yarn/npm `run` command. E.g, in `package.json`:

```
  "scripts": {
    "migrate": "db-migrate"
  }
```

And running either `npm run migrate` or `yarn migrate` will always trigger exit code 1.

**Comment by naxxster** [comment]
I think there is same bug in the db:drop command.

**Comment by ClaytonNorthey92** [comment]
@wzrdtales is there any progress made on this issue?  if not, I may be able to help.  Looking to use this functionality in an npm script and it functions correctly besides the exit status.

**Comment by wzrdtales** [comment]
Edit: actually https://github.com/db-migrate/node-db-migrate/commit/486cb78 there have been some changes, need to validate, that this problem was fixed. This was some while ago though.

**Comment by pc-jedi** [comment]
I updated to 0.11.2 to validate that the issue still persists.
Sadly the issue has not been fixed yet.

**Comment by wzrdtales** [comment]
Ok thanks verifying. Have a few minutes right now :) will push out a fix

**Comment by wzrdtales** [comment]
0.11.3 should deal with it. thanks for your patience though, I hope to
